# Databricks App runtime config for C360 Consumption Analytics
# See: https://docs.databricks.com/aws/en/dev-tools/databricks-apps/app-runtime
command:
  - streamlit
  - run
  - app.py
  - --server.headless
  - "true"
env:
  - name: STREAMLIT_GATHER_USAGE_STATS
    value: "false"
  # --- Same-workspace: SQL warehouse in this app's workspace ---
  # - name: DATABRICKS_WAREHOUSE_ID
  #   valueFrom: sql_warehouse
  # Or DATABRICKS_HTTP_PATH. If unset, app shows sidebar input for HTTP path.
  # --- Other-workspace: SQL warehouse in a different workspace ---
  # Set all three (host and path as value, token via valueFrom secret):
  # - name: REMOTE_WORKSPACE_HOST
  #   value: "other-workspace.cloud.databricks.com"
  # - name: REMOTE_HTTP_PATH
  #   value: "/sql/1.0/warehouses/<warehouse-id>"
  # - name: REMOTE_DATABRICKS_TOKEN
  #   valueFrom: remote_databricks_token
