# Databricks App runtime config for C360 Consumption Analytics
# See: https://docs.databricks.com/aws/en/dev-tools/databricks-apps/app-runtime
command:
  - streamlit
  - run
  - app.py
  - --server.headless
  - "true"
env:
  - name: STREAMLIT_GATHER_USAGE_STATS
    value: "false"
  # --- Same-workspace: SQL warehouse in this app's workspace ---
  # - name: DATABRICKS_WAREHOUSE_ID
  #   valueFrom: sql_warehouse
  # Or DATABRICKS_HTTP_PATH. If unset, app shows sidebar input for HTTP path.
  # --- Other-workspace: SQL warehouse in a different workspace ---
  # When REMOTE_WORKSPACE_HOST and REMOTE_HTTP_PATH are set, you must also:
  # 1. Add a Secret app resource: Configure → App resources → + Add resource → Secret;
  #    set resource key to "remote_databricks_token" (scope/key = where the other workspace's PAT is stored).
  # 2. Uncomment REMOTE_DATABRICKS_TOKEN below.
  # - name: REMOTE_WORKSPACE_HOST
  #   value: "other-workspace.cloud.databricks.com"
  # - name: REMOTE_HTTP_PATH
  #   value: "/sql/1.0/warehouses/<warehouse-id>"
  # - name: REMOTE_DATABRICKS_TOKEN
  #   valueFrom: remote_databricks_token
